import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RFMW INNOVATIONS LAB PVT. LTD.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="http://www.irfmw.com/assets/img/logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://www.irfmw.com/">RFMW</a> Demo
        </h1>
      </main>
    </div>
  )
}
